{{- $env := list }}
{{- range $key, $value := .Values.config.secrets.data }}
{{- $env = append $env (printf "%s=%s" (upper $key) $value) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ska-ser-bar-ui.name" . }}
  namespace: {{ template "ska-ser-bar-ui.namespace" . }}
  labels:
    {{- include "ska-ser-bar-ui.labels" . | nindent 4 }}
data:
  env: {{ printf "%s" (b64enc (join "\n" $env)) }}