image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_IMAGE: 'node:21'

stages:
  - dependencies
  - lint
  - accessibility
  - build
  - scan
  - pages
  - publish

include:
    # TS linting and unit testing
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/js-lint.gitlab-ci.yml'
    ref: st-2297-adopt-ska-base-image
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/js-audit.gitlab-ci.yml'
    ref: st-2297-adopt-ska-base-image
    # Accessibility
  - template: 'Verify/Accessibility.gitlab-ci.yml'
    # OCI Images
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'
    # Helm Chart
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'
    # Tag Based GitLab Release Management
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
    # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
